// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Base(children ...templ.Component) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Hello, TEMPL</title><script src=\"https://unpkg.com/htmx.org@1.9.12\" integrity=\"sha384-ujb1lZYygJmzgSwoxRggbCHcjc0rB2XoQrxeTUQyRjrOnlCoYta87iKBWq3EsdM2\" crossorigin=\"anonymous\"></script><!-- tailwind css --><link href=\"/static/css/tailwind.css\" rel=\"stylesheet\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, child := range children {
			templ_7745c5c3_Err = child.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- htmx --><span class=\" fusion-imageframe imageframe-none imageframe-1 peak-ignore\" style=\"border:10px solid #ffffff;\"><img fetchpriority=\"high\" decoding=\"async\" width=\"800\" height=\"600\" alt=\"Acrylglas\" title=\"ac23012\" src=\"https://local.kevin-fechner.site/image/?url=https://sks.mokka-webdesign.com/wp-content/uploads/2023/01/ac23012.png&amp;f=jpeg&amp;q=80\" class=\"img-responsive wp-image-32057\" srcset=\"https://local.kevin-fechner.site/image/?url=https://sks.mokka-webdesign.com/wp-content/uploads/2023/01/ac23012-200x150.png&amp;f=jpeg&amp;q=80&amp;w=200 200w, https://local.kevin-fechner.site/image/?url=https://sks.mokka-webdesign.com/wp-content/uploads/2023/01/ac23012-400x300.png&amp;f=jpeg&amp;q=80&amp;w=400 400w, https://local.kevin-fechner.site/image/?url=https://sks.mokka-webdesign.com/wp-content/uploads/2023/01/ac23012-600x450.png&amp;f=jpeg&amp;q=80&amp;w=600 600w, https://local.kevin-fechner.site/image/?url=https://sks.mokka-webdesign.com/wp-content/uploads/2023/01/ac23012.png&amp;f=jpeg&amp;q=80&amp;w=800 800w, \" sizes=\"(max-width: 800px) 100vw, 400px\"></span><script src=\"https://unpkg.com/htmx.org@1.9.10\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
